# Generated by Django 3.1.7 on 2021-03-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upload_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
