# Generated by Django 3.1.7 on 2021-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210330_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('tiny_image', models.ImageField(upload_to='', verbose_name='jam_images/')),
                ('description_html', models.TextField()),
                ('publicly_lsited', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(upload_to='cover_images/'),
        ),
    ]
